import{showPopup as p,showToast as a}from"./shared.js";let o=[];fetch("plugins-data.json").then(e=>e.json()).then(e=>{o=e,renderPlugins()}).catch(e=>{console.error("Error loading plugins data:",e)});const r=document.getElementById("plugins-container"),i=document.getElementById("sort-select"),c=document.getElementById("show-broken");function k(e){const n=document.createElement("div");n.className="plugin-card";let t="";switch(e.status){case"working":t="status-working";break;case"warning":t="status-warning";break;case"broken":t="status-broken";break}const s=e.authors.join(", ");n.innerHTML=`
    <div class="plugin-header">
        <h3 class="plugin-name">${e.name}</h3>
        <span class="plugin-status ${t}">${e.status}</span>
    </div>
    <div class="plugin-author">By: ${s}</div>
    <div class="plugin-description">${e.description}</div>
    <div class="plugin-buttons">
        <button class="plugin-button source-button" data-url="${e.sourceUrl}">Source Code</button>
        <button class="plugin-button plugin-copy-button" data-status="${e.status}" data-url="${e.installUrl}" data-warning="${e.warningMessage||""}">Copy Link</button>
    </div>
`;const l=n.querySelector(".source-button"),d=n.querySelector(".plugin-copy-button");return l.addEventListener("click",()=>{window.open(e.sourceUrl,"_blank")}),d.addEventListener("click",()=>{if(e.status==="working")u(e.installUrl),a(`Link for ${e.name} copied to clipboard!`);else{const b=e.status==="broken"?"Installing broken plugins may crash your client or cause unexpected behavior.":"This plugin may not work as expected.",g=e.status==="broken"?"This plugin is broken":"This plugin is partially broken";p({title:"Warning!",message:b,infoBox:e.warningMessage||"",primaryButton:{text:"Copy Anyway",action:()=>{u(e.installUrl),a(`Link for ${e.name} copied to clipboard!`),hidePopup()}},secondaryButton:{text:"Cancel",action:()=>hidePopup()}})}}),n}function u(e){navigator.clipboard.writeText(e).catch(n=>{console.error("Failed to copy: ",n)})}window.renderPlugins=function(){r.innerHTML="";let n=[...o];switch(c.checked||(n=n.filter(t=>t.status!=="broken")),i.value){case"default":n.sort((t,s)=>t.status==="broken"&&s.status!=="broken"?1:t.status!=="broken"&&s.status==="broken"?-1:t.name.localeCompare(s.name));break;case"broken-first":n.sort((t,s)=>t.status==="broken"&&s.status!=="broken"?-1:t.status!=="broken"&&s.status==="broken"?1:t.name.localeCompare(s.name));break;case"alphabetical":n.sort((t,s)=>t.name.localeCompare(s.name));break}n.forEach(t=>{const s=k(t);r.appendChild(s)})},i.addEventListener("change",renderPlugins),c.addEventListener("change",renderPlugins),document.addEventListener("DOMContentLoaded",renderPlugins);
