import{showPopup as p,showToast as u}from"./shared.js";let l=[];function h(t){const o=localStorage.getItem("previousPluginsState");if(!o)return localStorage.setItem("previousPluginsState",JSON.stringify(t)),null;const e=JSON.parse(o),n=new Map(e.map(a=>[a.name,a])),s={updated:[],added:[]};for(const a of t){const r=n.get(a.name);r?(r.status!==a.status&&s.updated.push({name:a.name,oldStatus:r.status,newStatus:a.status}),n.delete(a.name)):s.added.push(a)}return localStorage.setItem("previousPluginsState",JSON.stringify(t)),s}function y(t){if(!t||t.updated.length===0&&t.added.length===0)return;const o=s=>{switch(s){case"working":return"\u2705";case"warning":return"\u26A0\uFE0F";case"broken":return"\u274C";default:return""}};let e="",n=!0;t.updated.length>0&&(e+='<h4 style="margin-top: 0px; margin-bottom: 5px;">\u{1F503} Status changes:</h4>',e+=t.updated.map(s=>`${s.name}: ${o(s.oldStatus)} ${s.oldStatus} \u2192 ${o(s.newStatus)} ${s.newStatus}`).join("<br>"),n=!1),t.added.length>0&&(e+=`<h4 ${n?'style="margin-top: 0px; margin-bottom: 5px;"':'style="margin-top: 25px; margin-bottom: 5px;"'}>\u{1F680} Added:</h4>`,e+=t.added.map(a=>`${a.name} (${o(a.status)} ${a.status})`).join("<br>")),p({title:"Plugin Changes Detected",message:"Here is a summary of plugin changes since your last visit:",infoBox:e,primaryButton:{text:"Got it!",action:()=>hidePopup()},secondaryButton:null})}const c=document.getElementById("featured-plugin-container");function k(t){const o=document.getElementById("featured-plugin-template");if(!o)return console.error("Featured plugin template not found!"),null;const n=o.content.cloneNode(!0).querySelector(".featured-plugin-card");if(!n)return console.error("Root .featured-plugin-card not found in template!"),null;const s=n.querySelector(".featured-plugin-name");s&&(s.textContent=t.name);const a=n.querySelector(".featured-plugin-author");a&&(a.textContent=`By: ${t.authors.join(", ")}`);const r=n.querySelector(".featured-plugin-description");r&&(r.textContent=t.description);const i=n.querySelector(".plugin-copy-button");return i&&i.addEventListener("click",b=>{b.stopPropagation(),d(t.installUrl),u(`Link for ${t.name} copied to clipboard!`)}),n.addEventListener("click",()=>{n.classList.toggle("expanded")}),n}function w(t){if(c&&(c.innerHTML="",t)){const o=k(t);o&&c.appendChild(o)}}fetch("plugins-data.json").then(t=>t.json()).then(t=>{l=t;const o=l.find(n=>n.name==="Plugins List");w(o);const e=h(t);e&&(e.updated.length>0||e.added.length>0)&&y(e),renderPlugins()}).catch(t=>{console.error("Error loading plugins data:",t)});const g=document.getElementById("plugins-container"),m=document.getElementById("sort-select"),f=document.getElementById("show-broken");function S(t){const o=document.createElement("div");o.className="plugin-card";let e="";switch(t.status){case"working":e="status-working";break;case"warning":e="status-warning";break;case"broken":e="status-broken";break}const n=t.authors.join(", ");o.innerHTML=`
    <div class="plugin-header">
        <h3 class="plugin-name">${t.name}</h3>
        <span class="plugin-status ${e}">${t.status}</span>
    </div>
    <div class="plugin-author">By: ${n}</div>
    <div class="plugin-description">${t.description}</div>
    <div class="plugin-buttons">
        <button class="plugin-button source-button" data-url="${t.sourceUrl}">Source Code</button>
        <button class="plugin-button plugin-copy-button" data-status="${t.status}" data-url="${t.installUrl}" data-warning="${t.warningMessage||""}">Copy Link</button>
    </div>
`;const s=o.querySelector(".source-button"),a=o.querySelector(".plugin-copy-button");return s.addEventListener("click",()=>{window.open(t.sourceUrl,"_blank")}),a.addEventListener("click",()=>{if(t.status==="working")d(t.installUrl),u(`Link for ${t.name} copied to clipboard!`);else{const r=t.status==="broken"?"Installing broken plugins may crash your client or cause unexpected behavior.":"This plugin may not work as expected.",i=t.status==="broken"?"This plugin is broken":"This plugin is partially broken";p({title:"Warning!",message:r,infoBox:t.warningMessage||"",primaryButton:{text:"Copy Anyway",action:()=>{d(t.installUrl),u(`Link for ${t.name} copied to clipboard!`),hidePopup()}},secondaryButton:{text:"Cancel",action:()=>hidePopup()}})}}),o}function d(t){navigator.clipboard.writeText(t).catch(o=>{console.error("Failed to copy: ",o)})}window.renderPlugins=function(){g.innerHTML="";let o=[...l];switch(f.checked||(o=o.filter(e=>e.status!=="broken")),m.value){case"default":o.sort((e,n)=>e.status==="broken"&&n.status!=="broken"?1:e.status!=="broken"&&n.status==="broken"?-1:e.name.localeCompare(n.name));break;case"broken-first":o.sort((e,n)=>e.status==="broken"&&n.status!=="broken"?-1:e.status!=="broken"&&n.status==="broken"?1:e.name.localeCompare(n.name));break;case"alphabetical":o.sort((e,n)=>e.name.localeCompare(n.name));break}for(const e of o){const n=S(e);g.appendChild(n)}},m.addEventListener("change",renderPlugins),f.addEventListener("change",renderPlugins),document.addEventListener("DOMContentLoaded",renderPlugins);
