import{showPopup as p,showToast as i}from"./shared.js";let u=[];function h(t){const a=localStorage.getItem("previousPluginsState");if(!a)return localStorage.setItem("previousPluginsState",JSON.stringify(t)),null;const e=JSON.parse(a),n=new Map(e.map(o=>[o.name,o])),r={updated:[],added:[]};for(const o of t){const s=n.get(o.name);s?(s.status!==o.status&&r.updated.push({name:o.name,oldStatus:s.status,newStatus:o.status}),n.delete(o.name)):r.added.push(o)}return localStorage.setItem("previousPluginsState",JSON.stringify(t)),r}function y(t){if(!t||t.updated.length===0&&t.added.length===0)return;const a=r=>{switch(r){case"working":return"\u2705";case"warning":return"\u26A0\uFE0F";case"broken":return"\u274C";default:return""}};let e="",n=!0;t.updated.length>0&&(e+='<h4 style="margin-top: 0px; margin-bottom: 5px;">\u{1F503} Status changes:</h4>',e+=t.updated.map(r=>`${r.name}: ${a(r.oldStatus)} ${r.oldStatus} \u2192 ${a(r.newStatus)} ${r.newStatus}`).join("<br>"),n=!1),t.added.length>0&&(e+=`<h4 ${n?'style="margin-top: 0px; margin-bottom: 5px;"':'style="margin-top: 25px; margin-bottom: 5px;"'}>\u{1F680} Added:</h4>`,e+=t.added.map(o=>`${o.name} (${a(o.status)} ${o.status})`).join("<br>")),p({title:"Plugin Changes Detected",message:"Here is a summary of plugin changes since your last visit:",infoBox:e,primaryButton:{text:"Got it!",action:()=>hidePopup()},secondaryButton:null})}const d=document.getElementById("featured-plugin-container");function k(t){const a=document.getElementById("featured-plugin-template");if(!a)return console.error("Featured plugin template not found!"),null;const n=a.content.cloneNode(!0).querySelector(".featured-plugin-card");if(!n)return console.error("Root .featured-plugin-card not found in template!"),null;const r=n.querySelector(".featured-plugin-name");r&&(r.textContent=t.name);const o=n.querySelector(".featured-plugin-author");o&&(o.textContent=`By: ${t.authors.join(", ")}`);const s=n.querySelector(".featured-plugin-description");s&&(s.textContent=t.description);const l=n.querySelector(".featured-copy-button");return l&&l.addEventListener("click",b=>{b.stopPropagation(),c(t.installUrl),i(`Link for ${t.name} copied to clipboard!`)}),n.addEventListener("click",()=>{n.classList.toggle("expanded")}),n}function w(t){if(d&&(d.innerHTML="",t)){const a=k(t);a&&d.appendChild(a)}}fetch("plugins-data.json").then(t=>t.json()).then(t=>{u=t;const a=u.find(n=>n.name==="Plugins List");w(a);const e=h(t);e&&(e.updated.length>0||e.added.length>0)&&y(e),renderPlugins()}).catch(t=>{console.error("Error loading plugins data:",t)});const g=document.getElementById("plugins-container"),m=document.getElementById("sort-select"),f=document.getElementById("show-broken");function S(t){const a=document.createElement("div");a.className="card plugin-card";let e="";switch(t.status){case"working":e="status-badge--working";break;case"warning":e="status-badge--warning";break;case"broken":e="status-badge--broken";break}const n=t.authors.join(", ");a.innerHTML=`
    <div class="plugin-header">
        <h3 class="plugin-name card__title">${t.name}</h3>
        <span class="status-badge ${e}">${t.status}</span>
    </div>
    <div class="plugin-author card__author">By: ${n}</div>
    <div class="plugin-description card__description">${t.description}</div>
    <div class="plugin-buttons">
        <button class="btn btn--secondary source-button" data-url="${t.sourceUrl}">Source Code</button>
        <button class="btn btn--primary plugin-copy-button" data-status="${t.status}" data-url="${t.installUrl}" data-warning="${t.warningMessage||""}">Copy Link</button>
    </div>
`;const r=a.querySelector(".source-button"),o=a.querySelector(".plugin-copy-button");return r.addEventListener("click",()=>{window.open(t.sourceUrl,"_blank")}),o.addEventListener("click",()=>{if(t.status==="working")c(t.installUrl),i(`Link for ${t.name} copied to clipboard!`);else{const s=t.status==="broken"?"Installing broken plugins may crash your client or cause unexpected behavior.":"This plugin may not work as expected.";p({title:"Warning!",message:s,infoBox:t.warningMessage||"",primaryButton:{text:"Copy Anyway",action:()=>{c(t.installUrl),i(`Link for ${t.name} copied to clipboard!`),hidePopup()}},secondaryButton:{text:"Cancel",action:()=>hidePopup()}})}}),a}function c(t){navigator.clipboard.writeText(t).catch(a=>{console.error("Failed to copy: ",a)})}window.renderPlugins=function(){g.innerHTML="";let a=[...u];switch(f.checked||(a=a.filter(e=>e.status!=="broken")),m.value){case"default":a.sort((e,n)=>e.status==="broken"&&n.status!=="broken"?1:e.status!=="broken"&&n.status==="broken"?-1:e.name.localeCompare(n.name));break;case"broken-first":a.sort((e,n)=>e.status==="broken"&&n.status!=="broken"?-1:e.status!=="broken"&&n.status==="broken"?1:e.name.localeCompare(n.name));break;case"alphabetical":a.sort((e,n)=>e.name.localeCompare(n.name));break}for(const e of a){const n=S(e);g.appendChild(n)}},m.addEventListener("change",renderPlugins),f.addEventListener("change",renderPlugins),document.addEventListener("DOMContentLoaded",renderPlugins);
