import{isFixedSearchFocused as w}from"./search.js";let a=window.scrollY;const n=document.querySelector(".fixed-banner"),u=document.getElementById("backToTopButton"),l=document.getElementById("menuButton"),p=document.getElementById("dropdownMenu");function r(){const t=window.scrollY,c=t>a;a=t;const i=t>15&&!n.classList.contains("show"),d=t<=15&&n.classList.contains("show")&&!w()&&!c;i?(n.classList.add("show"),n.classList.remove("hide")):d&&(n.classList.add("hide"),n.classList.remove("show"))}window.onscroll=()=>{const o=document.documentElement.scrollTop>400;u.style.display=o?"block":"none"},u.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})}),document.addEventListener("DOMContentLoaded",()=>{l.addEventListener("click",()=>{p.classList.toggle("visible")}),window.addEventListener("click",o=>{o.target!==l&&!l.contains(o.target)&&!p.contains(o.target)&&p.classList.remove("visible")})});export function showToast(o){const t=document.getElementById("toast");t.innerHTML=o,t.classList.add("show"),setTimeout(()=>t.classList.remove("show"),2e3)}export function showPopup({title:o,message:t,infoBox:c=null,primaryButton:i={text:"OK",action:()=>hidePopup()},secondaryButton:d={text:"Cancel",action:()=>hidePopup()},closeOnOutsideClick:m=!0}){let e=document.getElementById("custom-popup");e||(e=document.createElement("div"),e.id="custom-popup",e.classList.add("popup-container"),document.body.appendChild(e)),e.innerHTML=`
        <div class="popup-content">
            <div class="popup-title">${o}</div>
            <div class="popup-message">${t}</div>
            ${c?`<div class="popup-info-box">${c.replace(/\n/g,"<br>")}</div>`:""}
            <div class="popup-buttons">
                <button class="popup-button popup-secondary-button" id="popup-secondary-btn">${d.text}</button>
                <button class="popup-button popup-primary-button" id="popup-primary-btn">${i.text}</button>
            </div>
        </div>
    `,document.getElementById("popup-primary-btn").addEventListener("click",s=>{s.stopPropagation(),i.action()}),document.getElementById("popup-secondary-btn").addEventListener("click",s=>{s.stopPropagation(),d.action()}),m&&(e.querySelector(".popup-content").addEventListener("click",s=>{s.stopPropagation()}),e.addEventListener("click",()=>{hidePopup()})),e.style.display="flex",window.hidePopup=function(){e.style.display="none"}}export function hidePopup(){const o=document.getElementById("custom-popup");o&&(o.style.display="none")}function h(){r(),window.addEventListener("scroll",r)}window.onload=()=>{h()};
