import{isFixedSearchFocused as w}from"./search.js";let a=window.scrollY;const s=document.querySelector(".fixed-banner"),r=document.getElementById("backToTopButton"),d=document.getElementById("menuButton"),p=document.getElementById("dropdownMenu");function u(){const o=window.scrollY,c=o>a;a=o;const l=o>15&&!s.classList.contains("show"),n=o<=15&&s.classList.contains("show")&&!w()&&!c;l?(s.classList.add("show"),s.classList.remove("hide")):n&&(s.classList.add("hide"),s.classList.remove("show"))}window.onscroll=()=>{const t=document.documentElement.scrollTop>400;r.style.display=t?"block":"none"},r.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})}),document.addEventListener("DOMContentLoaded",()=>{d.addEventListener("click",()=>{p.classList.toggle("visible")}),window.addEventListener("click",t=>{t.target!==d&&!d.contains(t.target)&&!p.contains(t.target)&&p.classList.remove("visible")})});export function showToast(t){const o=document.getElementById("toast");o.innerHTML=t,o.classList.add("show"),setTimeout(()=>o.classList.remove("show"),2e3)}export function showPopup({title:t,message:o,infoBox:c=null,primaryButton:l={text:"OK",action:()=>hidePopup()},secondaryButton:n={text:"Cancel",action:()=>hidePopup()},closeOnOutsideClick:m=!0}){let e=document.getElementById("custom-popup");e||(e=document.createElement("div"),e.id="custom-popup",e.classList.add("popup-container"),document.body.appendChild(e)),e.innerHTML=`
        <div class="popup-content">
            <div class="popup-title">${t}</div>
            <div class="popup-message">${o}</div>
            ${c?`<div class="popup-info-box">${c.replace(/\n/g,"<br>")}</div>`:""}
            <div class="popup-buttons">
                ${n?`<button class="popup-button popup-secondary-button" id="popup-secondary-btn">${n.text}</button>`:""}
                <button class="popup-button popup-primary-button" id="popup-primary-btn">${l.text}</button>
            </div>
        </div>
    `,document.getElementById("popup-primary-btn").addEventListener("click",i=>{i.stopPropagation(),l.action()}),n&&document.getElementById("popup-secondary-btn").addEventListener("click",i=>{i.stopPropagation(),n.action()}),m&&(e.querySelector(".popup-content").addEventListener("click",i=>{i.stopPropagation()}),e.addEventListener("click",()=>{hidePopup()})),e.style.display="flex",window.hidePopup=()=>{e.style.display="none"}}export function hidePopup(){const t=document.getElementById("custom-popup");t&&(t.style.display="none")}function h(){window.location.href.toLowerCase().includes("purple-eyez.github.io/plugins-list")&&showPopup({title:"Migration Notice",message:"This website is moving to a new address!",primaryButton:{text:"Take Me There",action:()=>{window.location.href="https://plugins-list.pages.dev/"}},secondaryButton:null,closeOnOutsideClick:!1})}function g(){u(),window.addEventListener("scroll",u)}window.onload=()=>{h(),g()};
