import{isFixedSearchFocused as w}from"./search.js";let a=window.scrollY;const s=document.querySelector(".fixed-banner"),u=document.getElementById("backToTopButton"),l=document.getElementById("menuButton"),p=document.getElementById("dropdownMenu");function r(){const t=window.scrollY,c=t>a;a=t;const d=t>15&&!s.classList.contains("show"),n=t<=15&&s.classList.contains("show")&&!w()&&!c;d?(s.classList.add("show"),s.classList.remove("hide")):n&&(s.classList.add("hide"),s.classList.remove("show"))}window.onscroll=()=>{const o=document.documentElement.scrollTop>400;u.style.display=o?"block":"none"},u.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})}),document.addEventListener("DOMContentLoaded",()=>{l.addEventListener("click",()=>{p.classList.toggle("visible")}),window.addEventListener("click",o=>{o.target!==l&&!l.contains(o.target)&&!p.contains(o.target)&&p.classList.remove("visible")})});export function showToast(o){const t=document.getElementById("toast");t.innerHTML=o,t.classList.add("show"),setTimeout(()=>t.classList.remove("show"),2e3)}export function showPopup({title:o,message:t,infoBox:c=null,primaryButton:d={text:"OK",action:()=>hidePopup()},secondaryButton:n={text:"Cancel",action:()=>hidePopup()},closeOnOutsideClick:m=!0}){let e=document.getElementById("custom-popup");e||(e=document.createElement("div"),e.id="custom-popup",e.classList.add("popup-container"),document.body.appendChild(e)),e.innerHTML=`
        <div class="popup-content">
            <div class="popup-title">${o}</div>
            <div class="popup-message">${t}</div>
            ${c?`<div class="popup-info-box">${c.replace(/\n/g,"<br>")}</div>`:""}
            <div class="popup-buttons">
                ${n?`<button class="popup-button popup-secondary-button" id="popup-secondary-btn">${n.text}</button>`:""}
                <button class="popup-button popup-primary-button" id="popup-primary-btn">${d.text}</button>
            </div>
        </div>
    `,document.getElementById("popup-primary-btn").addEventListener("click",i=>{i.stopPropagation(),d.action()}),n&&document.getElementById("popup-secondary-btn").addEventListener("click",i=>{i.stopPropagation(),n.action()}),m&&(e.querySelector(".popup-content").addEventListener("click",i=>{i.stopPropagation()}),e.addEventListener("click",()=>{hidePopup()})),e.style.display="flex",window.hidePopup=()=>{e.style.display="none"}}export function hidePopup(){const o=document.getElementById("custom-popup");o&&(o.style.display="none")}function h(){r(),window.addEventListener("scroll",r)}window.onload=()=>{h()};
